import Head from "next/head";
import Link from "next/link";

import Typewriter from "typewriter-effect";

import SIndex from "../styles/Pages/Index.module.css";
import SCommon from "../styles/Common.module.css";

export default function Home() {
  return (
    <div className={SCommon.container}>
      <Head>
        <title>My site!</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <div className={SIndex.headerImg}>
            <div className={SIndex.headerOverlay}>
                <div className={SIndex.blackTSBoxTitle}>
                    <h1 className={SCommon.title}>
                        {" "}
                        <Typewriter
                            options={{
                                strings: ["Nathaniel Dean", "NineBall"],
                                autoStart: true,
                                loop: true,
                                deleteSpeed: 50,
                                pauseFor: 2000,
                            }}
                        />
                    </h1>
                </div>
                <div className={SIndex.blackTSBoxDesc}>
                    <p className={SCommon.description}>
                        Student, developer, and questionable graphics designer.
                    </p>
                </div>
            </div>
      </div>

      <main>
        <div className={SCommon.grid}>
          <Link href="/Projects" passHref>
            <div className={SCommon.card}>
              <b style={{fontSize: "120%"}}>My Projects</b>
              <p style={{fontSize: "100%"}}>All of my current public projects and what they do.</p>
            </div>
          </Link>

          <Link href="/Volunteer" passHref>
            <div className={SCommon.card}>
              <b style={{fontSize: "120%"}}>Volunteer Work and Open-Source contributions</b>
              <p style={{fontSize: "100%"}}>
                Here you can find some of the time I&apos;ve contributed to the
                community.
              </p>
            </div>
          </Link>

          <Link href="/Contact" passHref>
            <div className={SCommon.card}>
              <b style={{fontSize: "120%"}}>Contact Me</b>
              <p style={{fontSize: "100%"}}>If you wish to get in touch here is my contact info!</p>
            </div>
          </Link>

          <Link href="/AboutMe" passHref>
            <div className={SCommon.card}>
              <b style={{fontSize: "120%"}}>About Me</b>
              <p style={{fontSize: "100%"}}>Learn some more about me!</p>
            </div>
          </Link>
        </div>
      </main>

      <footer>
        <Link href="https://github.com/NineBallo/NewWebsite" passHref>
          <h4 className={SCommon.footerLink}>Made by ME!</h4>
        </Link>
      </footer>
    </div>
  );
}
